### ISSUE TITLE
Scrolling with the scrollbar controls causes fixed header to disappear in `TableVirtuoso` component on Firefox

### ISSUE THREAD

**Issue by wickstopher** [petyosi/react-virtuoso#861] opened 2023-03-13 17:16 UTC
**Describe the bug**
Using Firefox, the fixed header appears to be re-rendered continually as new content scrolls into view; this results in the header disappearing momentarily while fast scrolling through a larger table. 

**Reproduction**
This is demonstrable in the example table in the docs: https://virtuoso.dev/table-fixed-headers/. Grabbing the scrollbar and scrolling up and down to the bottom/top exhibits this "flashing".

**Expected behavior**
When using a fixed header (`fixedHeaderContent` prop to `TableVirtuoso`), the header is not rerendered/invisible while scrolling with the scrollbar controls.

**Desktop (please complete the following information):**

Browser: Firefox 110.0.1
OS: MacOS 13.2.1

**Screen Recording**

https://user-images.githubusercontent.com/1975810/224786538-b097637b-0ffe-4773-8d77-fc8cb0c93c98.mov

**Comment by petyosi** [comment] 2023-03-13 17:24
I can't reproduce that on my machine. Follow the issue template so that I can help further. Closing this till further details are provided.

**Comment by wickstopher** [comment] 2023-03-13 17:42
Apologies @petyosi, I should have specified that I am on Firefox/MacOS. I attempted to reproduce the issue on Chrome and could not, so it appears to be specific to Firefox. I've updated the issue title and initial description using the template.

**Comment by wickstopher** [comment] 2023-03-13 17:52
I've attached a screen recording of the issue as well

**Comment by petyosi** [comment] 2023-03-13 18:09
This exact example can be improved as the table is missing `table-layout: fixed` and column width setting. However, setting these does not fully fix the problem (as it appears to go away after a few scrolls). 

From what I skimmed, other users report discuss similar behavior in bugzilla: 

https://bugzilla.mozilla.org/show_bug.cgi?id=1745323
https://bugzilla.mozilla.org/show_bug.cgi?id=1585378
https://bugzilla.mozilla.org/show_bug.cgi?id=1795784

**Comment by petyosi** [comment] 2023-03-14 06:28
To extend further, there's no DOM mount/unmount of the header while scrolling (this can be observed in dev tools). This is a browser-specific bug which, as far as I see, has no means to be addressed. @wickstopher - feel free to take that further, I am happy to be corrected.

**Closed by petyosi** 2023-03-14 06:28 UTC
