### ISSUE TITLE
Using custom Scroller messes with stickyBottom behavior

### ISSUE THREAD

**Issue by lexahall** [petyosi/react-virtuoso#773] opened 2022-10-18 04:27 UTC
I'm implementing a chat feature, and I need to use a custom Scroller component. I've noticed that as soon as I implement this custom Scroller, the chat no longer stays scrolled to the bottom when new messages come in. I've made a code sandbox with a similar issue that you can see here: https://codesandbox.io/s/react-virtuoso-v1-chat-forked-nxmlsi?file=/src/App.tsx

As soon as you begin to type, the Scroller scrolls all the way back up to the start of the chat history. This is only an issue with the custom Scroller component.

**Comment by petyosi** [comment] 2022-10-18 06:12
Duplicate of #756

**Closed by petyosi** 2022-10-18 06:12 UTC
Labels: duplicate
