### ISSUE TITLE
[BUG]  Uncaught Error: ResizeObserver loop completed with undelivered notifications. 

### ISSUE THREAD

**Issue by Alic-Chen** [petyosi/react-virtuoso#1049] opened 2024-03-19 08:55 UTC
![react-virtuoso-issue](https://github.com/petyosi/react-virtuoso/assets/76934976/67f44a54-54fb-4403-9b2f-afe511f4cf74)

**Comment by NiestrojMateusz** [comment] 2024-03-19 10:17
We faced the same issue after upgrade to 4.7.x

React version we use: react@18.2.0

![image](https://github.com/petyosi/react-virtuoso/assets/15727415/16404584-199a-4232-9b79-755275fc110a)

**Comment by NiestrojMateusz** [comment] 2024-03-19 10:18
We faced the same issue after upgrade to 4.7.x with react@18.2.0

**Comment by petyosi** [comment] 2024-03-19 13:59
Can you try adding (and calling) the following hook to your application? You need to add it only once. Please let me know if this works for you @NiestrojMateusz @Alic-Chen 

```tsx
function useSuppressResizeObserverError() {
  React.useEffect(() => {
    const cb = (e: ErrorEvent) => {
      if (
        e.message ===
        "ResizeObserver loop completed with undelivered notifications."
      ) {
        e.stopImmediatePropagation();
        e.preventDefault();
      }
    };
    window.addEventListener("error", cb);
    return () => {
      window.removeEventListener("error", cb);
    };
  }, []);
}
```

To clarify, the error is harmless, in fact there was a working draft for the browsers to implement means of avoiding it.

**Comment by petyosi** [comment] 2024-03-20 13:44
Another way to silence this error if you're using webpack dev server is to set your dev server config like so:
```js
        devServer: {
          client: {
            overlay: {
              errors: true,
              warnings: false,
              runtimeErrors: false, // this eliminates the error. 
            },
          },
        },
```

**Comment by Alic-Chen** [comment] 2024-03-22 06:43
> Can you try adding (and calling) the following hook to your application? You need to add it only once. Please let me know if this works for you @NiestrojMateusz @Alic-Chen
> 
> ```tsx
> function useSuppressResizeObserverError() {
>   React.useEffect(() => {
>     const cb = (e: ErrorEvent) => {
>       if (
>         e.message ===
>         "ResizeObserver loop completed with undelivered notifications."
>       ) {
>         e.stopImmediatePropagation();
>         e.preventDefault();
>       }
>     };
>     window.addEventListener("error", cb);
>     return () => {
>       window.removeEventListener("error", cb);
>     };
>   }, []);
> }
> ```
> 
> To clarify, the error is harmless, in fact there was a working draft for the browsers to implement means of avoiding it.

I'm sorry! That doesn't solve my problem

**Comment by petyosi** [comment] 2024-03-22 08:48
@Alic-Chen can you reproduce your problem - either in a sandbox or in a repository, so that I can examine it? As far as I can tell, this eliminates the error in a sandbox environment.

**Comment by Alic-Chen** [comment] 2024-03-22 09:19
![image](https://github.com/petyosi/react-virtuoso/assets/76934976/d0463f57-885c-44d7-897e-89be37661c79)

I have a requirement, the image is obtained from the database, the image height is adaptive according to the width, and do lazy loading processing, when I scroll the page, the console will keep printing "Uncaught Error: ResizeObserver loop completed with undelivered notifications. ", the page will continue to blink until the console stops printing errors. So I'm guessing it's a mistake. Excuse me next useSuppressResizeObserverError invoke this method should be in what place? Can you provide me with a demo? Thank you!

**Comment by petyosi** [comment] 2024-03-22 09:42
@Alic-Chen I believe you're facing a different problem than the one I had in mind. Most likely, you're trying to do something that the virtuoso grid does not support. It needs static-sized, same-size items to work correctly.

I believe that my instructions for the hook above are clear enough, However, they will not help you.

**Comment by markwoon** [comment] 2024-03-24 20:47
@petyosi Is the expectation that we need to use one of the workarounds above, or is there something react-virtuoso can do to avoid this warning?

**Comment by petyosi** [comment] 2024-03-25 07:05
@markwoon I'm trying to gather enough details from the users to understand if the hook is a viable solution. Once I know enough, I will most likely include it in the component initialization. Does it work for you?

The webpack dev server problem is not solvable from the component, I'm afraid. They bind to it unconditionally, as far as I can tell. 

To clarify, the reason why this error occurs is that the component reacts to item resizing and re-fills with new items. This is a legit approach. if I delay the action with something like `requestAnimationFrame`, the component would be much more sluggish when scrolling.

**Comment by Methuselah96** [comment] 2024-03-25 14:01
I am experiencing this error in Cypress, and unfortunately Cypress also listens to `error` events and fails the test if an error is encountered. I tried the above solution, but the Cypress error event handler is getting called before `useSuppressResizeObserverError`'s error callback.

**Comment by petyosi** [comment] 2024-03-25 15:14
@Methuselah96 - I'm not a cypress user, but it looks like this issue is very relevant? https://github.com/cypress-io/cypress/issues/8418. Can't deduct a definitive answer on how to do it, though. Please let me know if you figure something out.

**Comment by paulincai** [comment] 2024-03-28 19:33
@petyosi as I understand you are looking for some user feedback, I implemented the hook. It blocks most of the errors now however there are still some which are not blocked. I noticed that those which are not blocked are mostly occurring when a new react route loads (e.g. I am moving from a user profile to another user profile and then to the main wall of feeds). I use the "simple" Virtuoso (no grid/table etc)
When I scroll in a Virtuoso list is where you can see all those blocked errors.


![Screenshot 2024-03-28 at 11 29 25 PM](https://github.com/petyosi/react-virtuoso/assets/26188915/931cc08a-4cdf-4360-bb0e-98a1125ed239)

**Comment by Methuselah96** [comment] 2024-03-28 20:41
I wonder if using `useLayoutEffect` instead of `useEffect` would help with the errors that show up when a new route loads?

**Comment by petyosi** [comment] 2024-03-29 05:56
@paulincai - my guess is that you're using the hook somewhere in a specific route. I think it's better to put it on an app level so that it's executed once, no point in doing re-subscriptions. Let me know if my guess is correct.

**Comment by paulincai** [comment] 2024-03-29 13:51
@petyosi unfortunately I was at the top of React - top most component that is mounted on the generic ```id='app'``` in the initial HTML. Meanwhile, I moved it into my startup which runs before React even renders.
![Screenshot 2024-03-29 at 5 51 15 PM](https://github.com/petyosi/react-virtuoso/assets/26188915/30902ca7-e3a8-440b-8cde-1d84c7e896ca)

**Comment by petyosi** [comment] 2024-03-29 13:55
I guess moving it there should have worked, not sure from your post. Hard to say what goes on in this case, a reproduction would help. 

I am not sure where this screenshot is from, looks like an error reporting tool (Centry?). If so, [check this thread](https://forum.sentry.io/t/resizeobserver-loop-limit-exceeded/8402).

**Comment by paulincai** [comment] 2024-03-29 13:57
I added a bit to my comment above. All those errors occur at the same url with no routing. The reporting tool is specific to MeteorJS. It just sends whatever the browser says (or the server)

**Comment by paulincai** [comment] 2024-03-29 14:01
I personally don't have a problem with them. I have options in the reporting tool to just ignore them and don't get notified for them. I just wanted to let you know that probably the frequency at which they are generated is high and the listener disregards some.

**Comment by petyosi** [comment] 2024-03-29 18:01
@paulincai (and everyone else in this thread) can you please test v4.7.7? Thank you!

**Comment by Methuselah96** [comment] 2024-03-29 18:25
v4.7.7 fixes the errors I was getting in Cypress, thanks!

**Comment by petyosi** [comment] 2024-04-01 08:28
This problem should be solved in v4.7.7.

**Closed by petyosi** 2024-04-01 08:28 UTC
Labels: bug

**Comment by paulincai** [comment] 2024-04-01 12:25
I can also confirm these messages are gone away 100%.

**Comment by carlcodes** [comment] 2024-04-02 16:41
thank you for fixing this!!

**Comment by Vicky-Dai** [comment] 2024-11-10 03:31
> Another way to silence this error if you're using webpack dev server is to set your dev server config like so:
> 
> ```js
>         devServer: {
>           client: {
>             overlay: {
>               errors: true,
>               warnings: false,
>               runtimeErrors: false, // this eliminates the error. 
>             },
>           },
>         },
> ```

Where should I put this one?

**Comment by Vicky-Dai** [comment] 2024-11-10 03:32
I found that every time I use the 'draft-js', this error pops up.
