### ISSUE TITLE
Scrollbar drift

### ISSUE THREAD

**Issue by codeMonkey82** [petyosi/react-virtuoso#519] opened 2021-12-08 10:19 UTC
**Describe the bug**
Scrollbar issue, seems to step out of sync in chrome... ? When you pull down on the scrollbar handle slowly it seems fine, but when pulling down more aggressively it the mouse cursor starts to get ahead of the handle, in other words it seems to drift ?

**Reproduction**
Have a look here for an example
https://stackblitz.com/edit/react-functional-components-fwksf4?file=index.js

Pull down quickly on the scrollbar handle and witness the drifting of the mouse cursor away from the handle

**To Reproduce**
Look at stack blitz

**Expected behavior**
Scrollbar handle stays with the user scrolling

**Desktop (please complete the following information):**
 - OS: Mac OSX Mojave 10.14.6
 - Browser - Chrome Version 96.0.4664.93 (Official Build) (x86_64)

**Comment by petyosi** [comment] 2021-12-08 12:08
Duplicate of #449

**Closed by petyosi** 2021-12-08 12:08 UTC
Labels: bug, duplicate, wontfix
