### ISSUE TITLE
[BUG] Scroll to the bottom of the table if just scroll down once

### ISSUE THREAD

**Issue by a-buyankin** [petyosi/react-virtuoso#746] opened 2022-09-06 12:30 UTC
**Describe the bug**
Scroll to the bottom of the table if just scroll down once

**Reproduction**
https://virtuoso.dev/table-fixed-columns/ 

**To Reproduce**
 1. go to https://virtuoso.dev/table-fixed-columns/ 
 2. scroll the example table horizontally to the right
 3. scroll down the table once
 4. the example table will scroll to the bottom unexpectedly

**Expected behavior**
 the table will scroll down once

**Desktop:**
 - OS: Windows 10.
 - Browser: Chrome 104.0.5112.102

![issue](https://user-images.githubusercontent.com/39588378/188634400-52b3fb8e-f2f3-42dd-91a4-9bc6a23961a1.gif)
![issue2](https://user-images.githubusercontent.com/39588378/188636140-73aadf30-298c-4f25-b8af-b2bef6e70f9e.gif)

**Comment by petyosi** [comment] 2022-09-06 12:59
Duplicate of #609

**Closed by petyosi** 2022-09-06 12:59 UTC
Labels: bug, duplicate
