### ISSUE TITLE
[BUG] Content Items and scroll flickering when forwardRef is used

### ISSUE THREAD

**Issue by eyesofdaveed** [petyosi/react-virtuoso#557] opened 2022-02-04 07:54 UTC
Hi,
I am getting this annoying items and scroll flickering bug, when I am passing a "List" component with "ref", using react forwardRef.

https://codesandbox.io/s/sandpack-project-forked-u3t0u

If you visit the link and start scrolling down, after the reaching the end of first visible items, you will see the BUG. Items start flickering and scroll might jump on and off. 

If you don't pass the ListBox component to the "List", you won't get the bug, so I am pretty sure it is related with how I am trying to forward the ref. Without forwarding the ref, obviously, you won't be able to scroll. I have tried couple different options on how to forward the ref, but I am always ending up having that flickering bug.

**To Reproduce**
1. Visit the link
2. Scroll down to the end of first visible items list
3. See error

**Desktop (please complete the following information):**
 - Both Chrome and Safari have this issue.
 
 I will appreciate any help or hint on how to fix this issues:)

**Comment by petyosi** [comment] 2022-02-04 08:03
Duplicate of #363

**Closed by petyosi** 2022-02-04 08:03 UTC
Labels: bug, enhancement
