### ISSUE TITLE
[BUG] Table with sticky columns have issue with border rendering on random rows

### ISSUE THREAD

**Issue by andrejtomas5** [petyosi/react-virtuoso#1042] opened 2024-02-29 11:48 UTC
**Describe the bug**
When using sticky columns for the table I've noticed that randomly for some rows the bottom border for `td` element is not shown and sometimes the row before that has a double bottom border. I checked in the DevTools and the styles seem to have been applied correctly but for some reason the border is not visible. The border reappears when I hover over the column or row.

**Codesanbox**
[Link to the codesanbox](https://codesandbox.io/p/sandbox/icy-wildflower-wq36lc?file=%2FApp.js%3A54%2C37)

**Expected behavior**
Each border should be rendered for the ` td` element and shouldn't disappear randomly when scrolling.

**Screenshots**
![image](https://github.com/petyosi/react-virtuoso/assets/128493709/d4c76606-9caa-44c5-a3ee-121e84ff355b)

**Desktop:**
 - OS: Windows
 - Browser: Chrome

**Additional context**
I tried to solve with by using `borderCollapse: 'collapse'` and adding a border to the `tr` element but the problem persists.

**Comment by petyosi** [comment] 2024-02-29 11:54
The sandbox does not work for some reason. Can this be a browser bug? If so, it's a matter of finding the right hack to force rendering. 
<img width="743" alt="image" src="https://github.com/petyosi/react-virtuoso/assets/13347/fdfee32a-07ff-4c5a-997b-ccf1d42a12cd">

**Comment by andrejtomas5** [comment] 2024-02-29 11:58
I apologize, i forgot to make the sandbox public, please take a look again.

**Comment by petyosi** [comment] 2024-03-01 06:58
I'm afraid that I can't reproduce the problem on my side, so closing.

**Closed by petyosi** 2024-03-01 06:58 UTC
Labels: bug

**Comment by szpindi** [comment] 2025-04-03 09:36
I think to replicate you should use bigger screen, i have the same case, on mac everything works but when i move the window to my monitor the issue appears

**Comment by petyosi** [comment] 2025-04-03 10:40
@szpindi This could be something, but I'm also testing on an external monitor (3008x1692). Can you share your exact specs and the browser?

**Comment by szpindi** [comment] 2025-04-03 10:44
@petyosi 3440x1440, issue on Chrome, when i open in Safari all works fine

**Comment by szpindi** [comment] 2025-04-03 10:47
@petyosi the borders actually worked fine until the latest chrome update

**Comment by petyosi** [comment] 2025-04-03 10:54
Is 3440x1440 the native resolution of this monitor (sounds like it is)?  You might want to try using another CSS for the borders, like outline or box shadow, or even background. 

Notice that this is more or less a browser/OS bug of the example I have given, quite far from the core functionality of the package.
