### ISSUE TITLE
atBottomStateChange not working in example page

### ISSUE THREAD

**Issue by Amatrasan** [petyosi/react-virtuoso#171] opened 2020-09-08 07:02 UTC
I use atBottomStateChange to track being at the bottom of the list. I ran a test example with a timer and adding new users, but it doesn't work even there. It is added only once, and then nothing happens, even if you add a construction like
```
useEffect(() => {
setTimeout(() => setCount(count => count + 1), 1000)
}, [count])
```
count increases, but the scroll to the last element (followOutput) does not work, and atBottomStateChange does not work when scrolling to the last element manually.

**Comment by petyosi** [comment] 2020-09-08 07:08
I am not 100% sure I understand the problem you describe. Can you post a link to the page which does not work? The best you can do is to use stackblitz or code sandbox and show what you mean.

**Comment by Amatrasan** [comment] 2020-09-09 08:28
https://stackblitz.com/run?file=example.js

atBottomStateChange not called when I reach the bottom

**Comment by petyosi** [comment] 2020-09-09 12:30
You need to save the stackblitz - the link above does not include it.

**Comment by Amatrasan** [comment] 2020-09-09 19:24
https://stackblitz.com/edit/react-hkpuhn?file=example.js

**Comment by petyosi** [comment] 2020-09-10 16:16
This example seems to be working fine as far as I can see. What's wrong with it?

**Comment by Amatrasan** [comment] 2020-09-15 09:14
Do you add new entries at the bottom when you reach the end of the list?

**Comment by petyosi** [comment] 2020-09-15 11:30
I think so - check the gif: 
https://giphy.com/gifs/react-virtuoso-hubEUiO7h1lMmbcmJ9

**Comment by Amatrasan** [comment] 2020-09-15 11:36
And this is what I see
https://recordit.co/TUYT9ctLR5

**Comment by petyosi** [comment] 2020-09-16 18:27
I am not sure what's the problem then. Tested it on macOS, all browsers. You can debug what goes on your side, that's one [possible starting point](https://github.com/petyosi/react-virtuoso/blob/master/src/engines/scrolledToBottomEngine.ts#L18).

**Comment by petyosi** [comment] 2020-11-26 16:13
Closing, unable to reproduce :(.

**Closed by petyosi** 2020-11-26 16:13 UTC
