### ISSUE TITLE
[BIG] Vertical Scroll exception when scrolling horizontally to the far right

### ISSUE THREAD

**Issue by hungtcs** [petyosi/react-virtuoso#836] opened 2023-01-29 09:33 UTC
**Describe the bug**

Scrolling won't stop until bottom is reached.

**Reproduction**

https://virtuoso.dev/table-fixed-columns/

**To Reproduce**
1. Go to <https://virtuoso.dev/table-fixed-columns/>
2. Drag the horizontal scrollbar to the right
3. Scroll use mouse wheel

**Screenshots**

![image](https://user-images.githubusercontent.com/11692935/215317395-28b5e4fe-6772-4ee0-80bf-dab134656533.png)

**Desktop**
 - OS: MacOS 12.6.2
 - Browser: Google Chrome 109.0.5414.87

**Comment by petyosi** [comment] 2023-01-29 11:15
Duplicate of #609

**Closed** 2023-01-29 11:15 UTC
Labels: bug
