### ISSUE TITLE
[BUG] Scrolling in tables broken in 2.3.2

### ISSUE THREAD

**Issue by markwoon** [petyosi/react-virtuoso#534] opened 2022-01-11 01:34 UTC
**Describe the bug**

Scrolling in tables no longer works after upgrading to 2.3.2 from 2.3.1.

This is while attempting to use react-virtuoso in tables using the method described in #42.

**Reproduction**
https://codesandbox.io/s/virtuoso-table-forked-jixu5

**To Reproduce**
1. Go to https://codesandbox.io/s/virtuoso-table-forked-jixu5
2. Set react-virtuoso version to 2.3.1
3. Scroll in table and see that things scroll properly
4. Set react-virtuoso version to 2.3.2 (or higher)
5. Scroll in table and see scrolling is not working

**Expected behavior**
Scrolling should work as in 2.3.1

I know you're not really supporting tables, but I would love to see a fix for this...

**Comment by petyosi** [comment] 2022-01-11 05:25
Duplicate of #533

**Closed by petyosi** 2022-01-11 05:25 UTC
Labels: bug
