### ISSUE TITLE
[BUG] `endReached` does not get triggered when initial data is too small

### ISSUE THREAD

**Issue by alyyousuf7** [petyosi/react-virtuoso#928] opened 2023-06-15 21:39 UTC
**Describe the bug**
When my initial data is too less, that it doesn't fill up the screen height, it triggers `endReached` only once. If the next set of data is also too less to fill up the screen, I expect `endReached` to be triggered.

However, this works fine if the first load or the second load of data is enough to fill the screen.

**Reproduction**
**To Reproduce**
1. Visit https://virtuoso.dev/endless-scrolling/
2. Open CodeSandbox for the example
3. Change `generateUsers` first parameter from 100 to 1 on line 10.
4. Refresh the page, and it is stuck on Loading.

**Expected behavior**
I expect `endReached` to be triggered once again when there is not enough data on screen, so the `generateUsers` can get triggered.

**Screenshots**
<img width="1255" alt="image" src="https://github.com/petyosi/react-virtuoso/assets/14050128/141dec68-34de-4fcf-b098-8ac2fa41ce3b">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

**Comment by petyosi** [comment] 2023-06-16 05:10
Duplicate of #924 and #919

**Closed by petyosi** 2023-06-16 05:10 UTC
Labels: bug
