### ISSUE TITLE
initialTopMostItemIndex doesn't work properly in Chrome

### ISSUE THREAD

**Issue by lesha1201** [petyosi/react-virtuoso#91] opened 2020-04-13 07:34 UTC
When I try to use `initialTopMostItemIndex`, the list doesn't render any items. I tried to open an example from official page. It works on https://virtuoso.dev/initial-index/ but it doesn't work when I open in StackBlitz. I decided to download and try to build it but it didn't work neither. Also I tried it in playground and it didn't work there too. But for some reason it works in Firefox.

![react-kn82nn-ohhw1t-StackBlitz-Google-Chrome-2020-04-13-10-27-06](https://user-images.githubusercontent.com/10157660/79101830-1c22ae00-7d72-11ea-83fd-15895a9adbc3.gif)

By the way it works when `initialTopMostItemIndex` is either first element or last

**Environment:**
OS: Windows 10 1909
Browser: Chrome 80 (tried with disabled extensions), Chrome 81 mobile (Android)
Virtuoso: 0.15

**Comment by petyosi** [comment] 2020-04-13 09:14
I just [forked the example from the page in StackBlitz](https://stackblitz.com/edit/react-l1eibb?file=example.js) and it works fine for me. Can you elaborate on any additional steps?

**Comment by lesha1201** [comment] 2020-04-13 09:44
@petyosi It happens for me without any additional steps. I thought that it can happen only for me but I also tried on mobile and it behaves the same. I just tried on mobile again and noticed that if I reload https://virtuoso.dev/initial-index/ sometimes the list disappears even there. Can you try https://virtuoso.dev/initial-index/ to open it on mobile (Chrome), scroll to bottom to see an example and reload several times?

I will try to reproduce it on my laptop (linux) later and will report once I do this

**Comment by lesha1201** [comment] 2020-04-13 10:35
Verified the same behavior on another device. It happens periodically
Video: https://www.dropbox.com/s/4foqhy0hu9sqttb/2020-04-13%2013-29-43.mkv?dl=0

**Comment by petyosi** [comment] 2020-04-13 11:52
This looks like a rendering glitch - the scrollbar is there, but the items are not visible. Can you inspect the elements? Also, What's this - Chrome OS or Linux?

**Comment by lesha1201** [comment] 2020-04-13 12:04
@petyosi There is no elements. If I use footer then there is only the footer. It happens on Windows 10 (first video), Android, Linux (second video) in Chrome

**Comment by lesha1201** [comment] 2020-04-13 12:36
I tried to log `items` in `VirtuosoList` and here is the result:

![image](https://user-images.githubusercontent.com/10157660/79120791-6e78c480-7d9c-11ea-922a-dafc3c650741.png)

This is how it looks without `initialTopMostItemIndex`:

![image](https://user-images.githubusercontent.com/10157660/79120850-949e6480-7d9c-11ea-98c3-59da7bc476fc.png)

**Comment by petyosi** [comment] 2020-04-13 13:40
I fully trust you, but I need to reproduce this on my side to figure out what's wrong.  Never seen such thing during the dev (and I refreshed the demo 20 times at least). It could be a difference in the sequence of DOM elements reported. 

Will fire up a Windows VM and see if it will break there.

**Comment by psirenny** [comment] 2020-04-14 13:49
I've run into this issue as well when there is no scroll bar because the list is small. I'm not sure if it's related. I've had success by omitting the prop for small lists.

**Comment by petyosi** [comment] 2020-04-14 16:23
> I've run into this issue as well when there is no scroll bar because the list is small. I'm not sure if it's related. I've had success by omitting the prop for small lists.

Does not seem related, you can post a repro in a separate issue. Thanks!

**Comment by petyosi** [comment] 2020-04-18 13:38
@lesha1201 I tested the demo from the site on Windows and Linux VMs, Latest Chrome, to no avail. I have no android device available (and in these times, there is no one to take such a device from). If you can run the setup locally, you can try and see if this #99 makes any changes, although it should not be related to it.

**Comment by toonvd** [comment] 2020-04-18 17:56
I can reproduce this. Will include it in my testing tommorow.

**Comment by lesha1201** [comment] 2020-04-19 09:09
@petyosi Yes, #99 didn't help. I notice that it only happens for big `totalCount` in `index` playground. If I set 100000 as `totalCount` then I don't have problem but when I set `totalCount` to 500000 then I have that problem. Also I think it depends on how comlex components because the problem happens also in Initial Index example but `totalCount` is only 1000 there

**Comment by petyosi** [comment] 2020-04-19 09:47
Thanks, that is a good insight. The extrapolation of scrollTop for large lists will break the position, I can reliably reproduce it now, so I will think over that. 

However, I still can't find the problem in the original example version.

**Comment by NerdCowboy** [comment] 2020-05-19 19:16
Not entirely sure if this is related, but also consistently having an issue where if I set the `initialTopMostItemIndex` to 1, it won't display the GroupedVirtuoso. I dug into the inspector and the first group header will be in the DOM though, but nothing else. Can't reproduce outside of my repo though, so 🤷‍♂️

Only workaround I found was to override the index to 0 if it's 1.

**Comment by petyosi** [comment] 2020-05-21 07:57
@NerdCowboy I think I saw a problem where setting the index to the group does not work. Could this be the case?

**Comment by NerdCowboy** [comment] 2020-05-21 15:06
@petyosi I don't think that's the issue as 0 is the first group header and 1 is it's first item and it fails if I set it to 1. Verified that appears to work just fine using one of your StackBlitz demos as well.

It's quite possible it's something on my end since I can't reproduce the issue outside of my repo. Just thought I'd chime in in case anyone else had the same issue.

**Comment by andrewfluck** [comment] 2021-01-21 13:16
I think that the issue I just opened yesterday evening (#268) could be related to this.

**Comment by petyosi** [comment] 2021-01-21 17:55
This thread mixes several problems from the v0.x era of the component; I will close it. An unresolved problem (which I need to look at) is the handling of extremely large lists (where the scrollTop should be extrapolated) [from this comment](https://github.com/petyosi/react-virtuoso/issues/91#issuecomment-616082134).

**Closed by petyosi** 2021-01-21 17:55 UTC
