### ISSUE TITLE
[Question] How can I scroll to bottom if dynamic height image

### ISSUE THREAD

**Issue by huudatk53** [petyosi/react-virtuoso#300] opened 2021-02-19 09:39 UTC
1. First time, scroll to bottom not working when I use image. I used scrollToIndex. I'm not sure the way I use it makes sense. 
2. Suppose, the conversation has a lot of images, each image has a different height and use reverse endless scrolling loadmore message
Which approach is better?

![image](https://user-images.githubusercontent.com/13384935/108486180-5fbe4080-72d0-11eb-8bf4-040c32635026.png)
![image](https://user-images.githubusercontent.com/13384935/108486649-deb37900-72d0-11eb-8c6e-bb0f6baf5eb2.png)

[https://codesandbox.io/s/kind-spence-0cv62?file=/src/Scroll.js](url)

**Comment by petyosi** [comment] 2021-02-20 06:15
Duplicate of #293.

**Closed by petyosi** 2021-02-20 06:15 UTC
Labels: duplicate

**Comment by huudatk53** [comment] 2021-02-23 10:45
I used onLoad in img
First time is ok, but whenever the image loaded, scroll to bottom. Like this
![error](https://user-images.githubusercontent.com/13384935/108832928-bd1efe00-75fe-11eb-900c-37b95d642b3f.gif)
