### ISSUE TITLE
Is prepending items available in GroupedVirtuoso?

### ISSUE THREAD

**Issue by ysael** [petyosi/react-virtuoso#279] opened 2021-01-29 20:17 UTC
https://virtuoso.dev/prepend-items/

We are trying to implement this example wile using GroupedVirtuoso and we get this error as soon as we start using the firstItemIndex property. 

![image](https://user-images.githubusercontent.com/1785595/106323103-dd001380-6244-11eb-831b-06760302cd12.png)

also wondering if we got this right: 

firstItemIndex = total of items to be loaded - the one we have loaded 

In our case we are grouping by date so `total of items to be loaded` is difficult if not impossible to calculate as we will need to take account for the header?  
![image](https://user-images.githubusercontent.com/1785595/106324299-e4c0b780-6246-11eb-9029-b3b526ac6817.png)

thanks a lot for the great work ❤️  and I will gladly contribute again if needed :)

**Comment by petyosi** [comment] 2021-01-30 09:07
Hey @ysael, 

Love to see you around! Unfortunately, pretending items in grouped mode is not supported yet, purely because of an algorithm that I need to fry my brain on. If you want to give it a go at some point, I would love to help!

Here's the code that takes [care of the "unshift" process](https://github.com/petyosi/react-virtuoso/blob/master/src/sizeSystem.ts#L300). Apart from the algorithm complexity (sizes, offsets, and group offsets need to be rebuilt), implementing this support should be fairly isolated to the size system. 

I might give this a go at some point too, the UI you have screenshotted is very tempting.

**Comment by petyosi** [comment] 2021-01-30 09:07
P.S. Forgot to confirm that your understanding of `firstItemIndex` is correct.

**Comment by ysael** [comment] 2021-01-31 00:02
Thanks a lot for the quick response, I will take a look asap! 👀

**Comment by ysael** [comment] 2021-02-02 15:08
quick question @petyosi do you know a way to achieve `prepending` items in grouped mode with the current code base? thanks again :)

**Comment by petyosi** [comment] 2021-02-02 15:22
I think you might achieve that by re-mounting the component (by passing a different `key` prop) and passing different `groupCounts` and `initialTopMostItemIndex`. Not an optimal solution, even if it works.

**Comment by muyiwaoyeniyi** [comment] 2021-02-07 06:58
+1

**Comment by jonathaneckman** [comment] 2021-02-20 20:08
I could use this as well. I tried to add the feature myself but I couldn't get there. The only thing I was able to shake out of the experiment that may be of value is an e2e example showing:

- a list of "events" grouped by day
- initial load shows current day at the top
- infinite scroll into the future (append)
- TODO: infinite scroll into the past (prepend)

Its [in my fork](https://github.com/jonathaneckman/react-virtuoso/blob/master/e2e/grouped-reverse-endless-scrolling.tsx) if you need it. Front end is not my specialty so sorry for the ugly code. 

![bidirectional-infinite-scroll-grouped-list](https://user-images.githubusercontent.com/11893200/108607258-47f8c200-738d-11eb-82f5-ad2d67f87fad.gif)

**Comment by acmatson** [comment] 2021-04-07 18:16
> I could use this as well. I tried to add the feature myself but I couldn't get there. The only thing I was able to shake out of the experiment that may be of value is an e2e example showing:
> 
> * a list of "events" grouped by day
> * initial load shows current day at the top
> * infinite scroll into the future (append)
> * TODO: infinite scroll into the past (prepend)
> 
> Its [in my fork](https://github.com/jonathaneckman/react-virtuoso/blob/master/e2e/grouped-reverse-endless-scrolling.tsx) if you need it. Front end is not my specialty so sorry for the ugly code.
> 
> ![bidirectional-infinite-scroll-grouped-list](https://user-images.githubusercontent.com/11893200/108607258-47f8c200-738d-11eb-82f5-ad2d67f87fad.gif)

We're implementing this scenario as well using GroupedVirtuoso. I came up with workarounds in the 0.x versions, but they have been very unstable. Love that this issue has visibility and looking forward to see this resolved in the codebase!

**Comment by mrodrigues95** [comment] 2021-07-24 17:17
Has anyone come up with a solution for this? I'm trying to implement a chat system where messages are grouped by dates but I am having a hard time getting this to work with prepending items and groups.

Is this possible with the current implementation?

**Comment by shachar731945** [comment] 2021-08-06 15:54
When is this feature planning to be worked on?

**Comment by petyosi** [comment] 2021-08-07 08:40
@shachar731945 are you willing to contribute or sponsor the project?

**Comment by shachar731945** [comment] 2021-08-07 11:30
https://github.com/petyosi/react-virtuoso/pull/380

Hi, This is the pull request I have added to this project two months ago.
If you do not recall, we have even spoken about this subject.

Regarding the comment, I did not want to diminish or disparage your
valuable work in any way.
It's just an issue that I need to know in my project.
Again, this comment did not mean to be personal in any way shape or form.

Thanks for the hard work and effort :)


‫בתאריך שבת, 7 באוג׳ 2021 ב-11:40 מאת ‪Petyo Ivanov‬‏ <‪
***@***.***‬‏>:‬

**Comment by nullablemind** [comment] 2021-08-10 07:57
> Hey @ysael,
> 
> Love to see you around! Unfortunately, pretending items in grouped mode is not supported yet, purely because of an algorithm that I need to fry my brain on. If you want to give it a go at some point, I would love to help!
> 
> Here's the code that takes [care of the "unshift" process](https://github.com/petyosi/react-virtuoso/blob/master/src/sizeSystem.ts#L300). Apart from the algorithm complexity (sizes, offsets, and group offsets need to be rebuilt), implementing this support should be fairly isolated to the size system.
> 
> I might give this a go at some point too, the UI you have screenshotted is very tempting.

I am ready to implement this feature. Could you, @petyosi, tell me what the problem is? So that I think about how to solve it.

**Comment by petyosi** [comment] 2021-08-11 06:29
@nullablemind it is not a problem, it is a missing implementation. If you would like to contribute, you can examine the size system and its tests to understand how the sizing data structures work.

**Comment by pthanh1703** [comment] 2022-05-10 12:21
+1

**Comment by Flaaj** [comment] 2022-09-17 16:58
Is it still a "problem" ? I managed to do two-way infinite scroll chat component with dynamically added data. It took me a while to figure out how to do it properly so I guess the "easy and user friendly implementation" is still not here, but I might be wrong. 

If any maintainer reads this - please message me if implementation is still needed so I can try to work on it

**Comment by petyosi** [comment] 2022-09-17 17:30
I am not understanding what you have done. You can recreate it in a sandbox and post a link here.

**Comment by aminmc** [comment] 2023-03-16 21:15
> Is it still a "problem" ? I managed to do two-way infinite scroll chat component with dynamically added data using react-virtuoso and it works quite perfect (although it jumps on prepending items when I try to add overscan / increaseViewportBy, but I dont need those properties after all). It took me a while to figure out how to do it properly so I guess the "easy and developer friendly implementation" is still not here, but I might be wrong.
> 
> If any maintainer reads this - please message me if implementation is still needed so I can try to work on it
> 
> Basically the main problem is getting correct firstItemIndex. In the API I'm using after fetching each page I get the total amount of messages in the chat, so I'm able to calculate firstItemIndex like this:
> 
> const firstItemIndex = totalCount - fetchedMessages.length - minPageNumberFetched * MESSAGES_PER_PAGE;

Hey @Flaaj do you have an example of this?  When the user scrolls up or down i'd like to reload the data instead of  adding to the local state which has the collection.  Any help would be appreciated.

**Comment by danielsantiago** [comment] 2023-03-31 15:54
@petyosi in our small startup we have just recently released a feature based on Virtuozo, and we are very happy with the result. I see that some new features are under the "sponsor-or-pr" label, in case it helps to give priority to this feature we have become sponsors. We hope that as our product grows we can also move up in the sponsor tier.

**Comment by petyosi** [comment] 2023-03-31 16:02
Thanks @danielsantiago - it certainly helps. I love this feature in general (it's the right thing to have) and I will try to make it happen in a reasonable timeframe.

**Comment by petyosi** [comment] 2023-04-03 13:45
@danielsantiago (or anyone following this thread): It would help me if you build and test this branch for your purposes. 

https://github.com/petyosi/react-virtuoso/compare/prepend-items 

I've left some examples in the doc comments. I will also add an example to the site once I test some more. 

https://github.com/petyosi/react-virtuoso/commit/a61459c61a9541dce6244d7979d0170726dc9adc#diff-a0a3eb436be6f2828cb19615696181cb3bbdeb884582c69bfd841ca206ae2da9

**Closed** 2023-04-04 10:31 UTC
Labels: enhancement, sponsor-or-pr

**Comment by petyosi** [comment] 2023-04-04 10:41
Here's an example of the group prepending in action: https://codesandbox.io/s/sandpack-project-forked-0tle24?file=/index.js
